### ISSUE TITLE
Crash when Multifactor Authentication is enabled

### ISSUE THREAD

**Issue by LorenzoRosmarino** [liamcottle/valorant.js#24]
Are you considering supporting MFA ?

I have MFA activated on my riot account, and the `authorize` method on the `API` class crashes.

```
parseTokensFromUrl(access_tokens.data.response.parameters.uri);
```
When MFA is active, their is no `parameters` property on `data.response`, but data about MFA instead.

**Comment by SpatzlHD** [comment]
I am going to take a look into this problem and open a PR to fix it! @liamcottle I hope this is ok for you 🙃

**Comment by liamcottle** [comment]
I haven't actually used the new MFA support in Riot Games yet. So I'm happy for you to PR this if you want.

I'm assuming we would need to implement a CLI tool that can be used to obtain your auth token, since this would now require the user to input an MFA code of some description.

It would probably work something like this:
- User runs CLI tool
- User provides username/password
- if multiple MFA options configured, user is asked to choose the MFA source (email/token generator/sms)
- User is asked to provide the MFA code
- CLI tool outputs the auth token
- User can then use this auth token when creating a new instance of the Valorant API client

**Comment by LorenzoRosmarino** [comment]
How would it work when this package is used in a backend server, where user doesn't have access to the CLI ?

**Comment by SpatzlHD** [comment]
Fortunately, Riot's only MFA method is a code via email. I had thought that the auth method simply returned a status that is either done or multifactor if the status is multifactor you can use a multifactor function that takes a code as a parameter. This then uses the session id stored from the normal auth function to perform the authentication.
So the code on the user side would look something like this:
```js

valorantApi.authorize('username', 'password').then((data) => {
    if(data.status === "multifactor"){
		valorantApi.multifactor('code').then(() => {
			//successful authentication
		})
	}else if(data.status === 'done'){
		//successful authentication
	}
}).catch((error) => {
    console.log(error);
});

```

**Comment by LorenzoRosmarino** [comment]
Any updates ?

**Comment by SpatzlHD** [comment]
I am working on it but currently I am not at home and riot is making this shit hard

**Comment by liamcottle** [comment]
Initial MFA support is now available for testing and feedback in the [feature/mfa-support](https://github.com/liamcottle/valorant.js/tree/feature/mfa-support) branch.

**Comment by LorenzoRosmarino** [comment]
Awesome ! Thanks a lot
I'm going to try it out very soon

**Comment by yash1441** [comment]
Is there any progress on the MFA support?
